name: Continuous Integration
on: [push]
jobs:
  config:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
        php-versions: ["7.4"]
        node-version: [16.x]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: unzip zip
        run: unzip -qq release.zip
      - name: Repository lampy
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: koromerzhin/lampy
          path: lampy
      - name: Zip artifact for deployment
        run: zip release.zip ./* -rq
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: config
          path: release.zip
  init:
    needs: config
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
        php-versions: ["7.4"]
        node-version: [16.x]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: config
      - name: unzip zip
        run: unzip -qq release.zip
      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: make node_modules
      - name: 'SET BDD'
        run: make bddset
      - name: Zip artifact for deployment
        run: zip release.zip ./* -rq
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: init
          path: release.zip
  docker:
    needs: init
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
        php-versions: ["7.4"]
        node-version: [16.x]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: init
      - name: unzip zip
        run: unzip -qq release.zip
      - name: 'Launch Lampy'
        run: make lampy
      - name: 'Image pull'
        run: make docker image-pull
      - name: 'Build containers'
        run: make docker deploy
      - name: 'sleep'
        run: make sleep 60
      - name: 'docker ls'
        run: make docker ls
      - name: Zip artifact for deployment
        run: zip release.zip ./* -rq
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: docker
          path: release.zip